media:
  path: images/projects
  public_path: images/projects

content:
  - name: projects
    label: Progetti
    type: file
    path: projects.json
    format: json
    list: true
    fields:
      - name: title
        label: Titolo
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        required: true
      - name: collaborator
        label: Collaboratore
        type: string
      - name: year
        label: Anno
        type: string
      - name: description
        label: Descrizione
        type: text
      - name: category
        label: Categoria
        type: select
        required: true
        options:
          - label: Editorial
            value: editorial
          - label: Packaging
            value: packaging
          - label: Book Cover
            value: book-cover
          - label: Brand Identity
            value: user-interface
      - name: tags
        label: Tag
        type: string
        list: true
      - name: mainImageUrl
        label: Immagine Principale
        type: image
      - name: gallery
        label: Galleria Immagini
        type: image
        list: true
      - name: externalLink
        label: Link Esterno
        type: string
      - name: featured
        label: In Evidenza
        type: boolean
      - name: order
        label: Ordine
        type: number
